# Generated by Django 5.2.16 on 2026-08-14 14:12

import django.core.validators
import django.db.models.deletion
import fleet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Vehicle display name', max_length=100)),
                ('imei', models.CharField(db_index=True, help_text='IMEI identifier', max_length=30, unique=True)),
                ('type', models.CharField(choices=[('SWEEPER', 'SWEEPER'), ('SMALL BELL TRUCK', 'SMALL BELL TRUCK'), ('COMPACTOR', 'COMPACTOR')], default='SWEEPER', max_length=50)),
                ('category', models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary')], default='Primary', max_length=50)),
                ('vehicle_number', models.CharField(blank=True, max_length=30, null=True)),
                ('serial_number', models.CharField(blank=True, help_text='Vehicle GPS device serial number', max_length=100, null=True)),
                ('api_key', models.CharField(default=fleet.models.generate_api_key, help_text='Secret API key assigned to this tracking device', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('moving', 'Moving'), ('idle', 'Idle'), ('offline', 'Offline')], db_index=True, default='offline', max_length=20)),
                ('speed', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('fuel', models.FloatField(default=100.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('battery', models.FloatField(default=100.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('latitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('location', models.CharField(blank=True, max_length=255)),
                ('total_distance', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('today_distance', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('engine_on', models.BooleanField(default=False)),
                ('gps_signal', models.CharField(default='strong', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='fleet.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(blank=True, max_length=255)),
                ('start_latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('start_longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('end_latitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('end_longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('distance', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='started', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='fleet.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='fleet.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='GPSLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('speed', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('fuel', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('battery', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_locations', to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'GPS Location',
                'verbose_name_plural': 'GPS Locations',
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['status', '-last_updated'], name='fleet_vehic_status_dc9cbb_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['vehicle', '-started_at'], name='fleet_trip_vehicle_0f7f7c_idx'),
        ),
        migrations.AddIndex(
            model_name='gpslocation',
            index=models.Index(fields=['vehicle', '-recorded_at'], name='fleet_gpslo_vehicle_2ac163_idx'),
        ),
    ]
