# Generated by Django 5.2.17 on 2026-09-19 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_alter_vehicle_device_id_uploadroute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadroute',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='uploadroutehistory',
            name='vehicle',
        ),
        migrations.AlterField(
            model_name='uploadroute',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='AssignedRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('coordinates', models.JSONField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_routes', to='fleet.vehicle')),
            ],
        ),
    ]
